### PR TITLE
Organization-wide Workflow Add Instructions

### PR DESCRIPTION
**Pull request by naveensrinivasan**
I picked up the PR #151

### CODE REVIEW

**Review by olivekl — APPROVED** [review]

**Comment by naveensrinivasan** [comment]
@azeemshaikh38 @justaugustus @laurentsimon I need a 👍 to merge this in.

**Review by laurentsimon — COMMENTED** [review]
Is the multi-repo tool ready?
Last time I checked, it would need a bit of logic to detect whether a previous PR was sent or not, in order to avoid duplication of issues.

**Comment by naveensrinivasan** [comment]
> Is the multi-repo tool ready?
> Last time I checked, it would need a bit of logic to detect whether a previous PR was sent or not, in order to avoid duplication of issues.

TBH I don't know. We can close this PR if it isn't ready. I picked up the long-running PR to close things.

**Comment by laurentsimon** [comment]
> > Is the multi-repo tool ready?
> > Last time I checked, it would need a bit of logic to detect whether a previous PR was sent or not, in order to avoid duplication of issues.
> 
> TBH I don't know. We can close this PR if it isn't ready. I picked up the long-running PR to close things.

I think it'd be good to iron out some of the problems. I'm just hesitant to release this if people start finding problems. I think the main feature that would be useful it avoid spamming if a person provides a repository where an issue is already opened. That'd a cool PR to work on though.

Wdut?

**Review by justaugustus — CHANGES_REQUESTED** [review]
@naveensrinivasan -- In lieu of updating the instructions, I would actually remove any mentions on the tool (, but not the tool itself).

I merged some initial fixes to `multi-repo-action` in https://github.com/ossf/scorecard-action/pull/301, but it is still not in a working state and I think leaving instructions in about it may cause more overhead than we need.

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan -- In lieu of updating the instructions, I would actually remove any mentions on the tool (, but not the tool itself).
> 
> I merged some initial fixes to `multi-repo-action` in #301, but it is still not in a working state and I think leaving instructions in about it may cause more overhead than we need.


I agree. There isn't any mention of the tool other than in its own folder and README. I will update the README with Work In Progress.

**Comment by naveensrinivasan** [comment]
closing this for https://github.com/ossf/scorecard-action/pull/776

**Pull request closed without merging**
