### PR TITLE
image: Build the `scorecard` command from this repo's wrapper instead of copying

### PR DESCRIPTION
**Pull request by justaugustus**
PRs like https://github.com/ossf/scorecard-action/pull/312 and https://github.com/ossf/scorecard-action/pull/313 demonstrate that it's possible to drift between what is built for the scorecard action container image and what dependencies are in the Golang-based action, which means the behavior can be unpredictable and can lead to breakages, as seen in https://github.com/ossf/scorecard-action/issues/277.

This PR is a small change, which ensures we only need to update the scorecard dependency in a single place.
I also added some baseline testing docs, as a treat!

Commits:

- image: Build the `scorecard` command from source instead of copying

  This is another step in getting rid of the bash-based entrypoint.
  By building from the scorecard-action source, we're ensuring a few
  things:

  - The existing entrypoint leverages the wrapper code
  - We only track the scorecard dependency in a single location (go.mod)

- image: Include event paths for testing scenarios

Signed-off-by: Stephen Augustus <foo@auggie.dev>

### CODE REVIEW

**Comment by justaugustus** [comment]
(I'm going to save any thoughts I had about being clever with the bash script for a future PR to keep the diff small.)

**Comment by laurentsimon** [comment]
One worry is time to run the Action. Compiling scorecard takes several minutes, so it would be great to use pre-build containers. We can compile the container using the Dockefile you've updated.  

How about temporarily renaming this Dockefile to Dockerfile.go? Otherwise the e2e tests will start breaking immediately. We have this issue https://github.com/ossf/scorecard-action/issues/236 that needs to be resolved before we can move to the go code

Wdut?

**Comment by laurentsimon** [comment]
One worry is time to run the Action. Compiling scorecard takes several minutes, so it would be great to use pre-build containers. We can compile the container using the Dockefile you've updated.  

How about temporarily renaming this Dockefile to Dockerfile.go? Otherwise the e2e tests will start breaking immediately. We have this issue https://github.com/ossf/scorecard-action/issues/236 that needs to be resolved before we can move to the go code

Wdut?

**Comment by azeemshaikh38** [comment]
The Dockerfile changes should be pushed to `golang-staging` branch. That'll automatically test this change for Golang action against the current bash action. Apart from that LGTM.

**Comment by spencerschrock** [comment]
This PR is old and appears to have been addressed by https://github.com/ossf/scorecard-action/pull/750

**Comment by justaugustus** [comment]
> This PR is old and appears to have been addressed by https://github.com/ossf/scorecard-action/pull/750

Thanks for catching this and cleaning up, @spencerschrock!

**Pull request closed without merging**
