### PR TITLE
✨ Add more info to logs

### PR DESCRIPTION
**Pull request by laurentsimon**
Add more info to logs to help troubleshooting problems.
There's been a new issue on a problem that we've seen before https://github.com/ossf/scorecard-action/issues/154

cc @naveensrinivasan let's add this to our list of unit tests once we've figured the problem.

```release-notes
Add more info to logs
```

closes https://github.com/ossf/scorecard-action/issues/156

### CODE REVIEW

**Review by naveensrinivasan — COMMENTED** [review]
LGTM! Can we please also include this in the `go` code?

**Comment by laurentsimon** [comment]
> LGTM! Can we please also include this in the `go` code?

IIUC the go code in out of sync already. Example; it's reading from the GITHUB_EVENT_PATH file https://github.com/ossf/scorecard-action/blob/main/options/options.go#L229 instead of using https://github.com/ossf/scorecard-action/blob/main/github/github.go#L115


I'll create an issue for sync'ing the code.

**Comment by azeemshaikh38** [comment]
> LGTM! Can we please also include this in the `go` code?

+1 to this. It's easier to just do this as we go along. Even better, we can consider only adding updates to the Golang code instead of bash.

**Comment by laurentsimon** [comment]
> > LGTM! Can we please also include this in the `go` code?
> 
> +1 to this. It's easier to just do this as we go along. Even better, we can consider only adding updates to the Golang code instead of bash.

I'll try that. I cannot add code only to go code though, because I have no idea if it does the same as entrypoint.sh. AT least it should be used by our own repos to stage a release.

**Comment by laurentsimon** [comment]
please also advise how you'd like me to test. It used to be a file with the content, now it's an live API call to GitHub. I think I'll have to use the mock library; but tell me if you had something else in mind. Also, an example will be appreciated. @naveensrinivasan could you point me to a good example in scorecard you'd like me to follow?

**Comment by azeemshaikh38** [comment]
> please also advise how you'd like me to test. It used to be a file with the content, now it's an live API call to GitHub. I think I'll have to use the mock library; but tell me if you had something else in mind. @naveensrinivasan could you point me to a good example in scorecard you'd like me to follow?

Do you mean test Golang code? @rohankh532 is working on adding e2e tests similar to how we test bash script today so can skip that for now. And the bash changes should get tested using the e2e we have already.

**Comment by laurentsimon** [comment]
> > please also advise how you'd like me to test. It used to be a file with the content, now it's an live API call to GitHub. I think I'll have to use the mock library; but tell me if you had something else in mind. @naveensrinivasan could you point me to a good example in scorecard you'd like me to follow?
> 
> Do you mean test Golang code? @rohankh532 is working on adding e2e tests similar to how we test bash script today so can skip that for now. And the bash changes should get tested using the e2e we have already.

The code change in `go` now queries a GitHub API to retrieve repo information (instead of using a file content `GITHUB_EVENT_PATH`), so I need to mock the API if I want to have unit tests for it. The tests are failing right now, and I suspect it's because of that. I'm more than happy to leave this to @rohankh532... but that means `go` changes cannot be included in this PR... Wdut?

**Comment by naveensrinivasan** [comment]
@laurentsimon  Is this still valid?

**Comment by laurentsimon** [comment]
Let's close.

**Pull request closed without merging**
