### PR TITLE
Minor release v2.1.0

### PR DESCRIPTION
**Pull request by laurentsimon**
Signed-off-by: laurentsimon <64505099+laurentsimon@users.noreply.github.com>

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
> Signed-off-by: laurentsimon [64505099+laurentsimon@users.noreply.github.com](mailto:64505099+laurentsimon@users.noreply.github.com)

What will the release contain? The new OSV scanner?

**Comment by laurentsimon** [comment]
correct. ouch. I probably need to update the go.mod

**Comment by laurentsimon** [comment]
> correct. ouch. I probably need to update the go.mod

Already done.

**Review by naveensrinivasan — APPROVED** [review]
Thanks!!

**Comment by laurentsimon** [comment]
Pre-release run succeeded

**Pull request merged**
