### PR TITLE
feat: Disable pull_request_target

### PR DESCRIPTION
**Pull request by laurentsimon**
Signed-off-by: laurentsimon <laurentsimon@google.com>

This trigger is dangerous so let's disable it.

### CODE REVIEW

**Comment by laurentsimon** [comment]
There does not seem to be any uses of scorecard with this trigger at the moment https://github.com/search?q=pull_request_target++ossf%2Fscorecard-action&type=code

**Review by naveensrinivasan — COMMENTED** [review]
Can you please add some links as to why this is dangerous?

**Comment by laurentsimon** [comment]
> Can you please add some links as to why this is dangerous?

Done, as part of the error message. PTAL

**Review by naveensrinivasan — APPROVED** [review]
Thanks

**Pull request merged**
